on:
  push:
    branches: [master]
name: CI
jobs:
  flatter:
    name: "Flatter"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:46
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      id: flatpak
      uses: andyholmes/flatter@main
      with:
        files: moe.japan7.karaberus.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Deploy Repository
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        folder: ${{ steps.flatpak.outputs.repository }}
        target-folder: repo
