on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CI
jobs:
  flatter:
    name: "Flatter"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:48
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v5

      #    - name: Setup GPG
      #      id: gpg
      #      uses: crazy-max/ghaction-import-gpg@v5
      #      with:
      #        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build
      id: flatpak
      uses: andyholmes/flatter@main
      with:
        files: moe.japan7.karaberus.yml
        #        gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Deploy Repository
      uses: JamesIves/github-pages-deploy-action@releases/v4
      if: github.ref == 'refs/heads/master'
      with:
        folder: ${{ steps.flatpak.outputs.repository }}
        target-folder: repo
