on:
  push:
    branches: [master]
name: CI
jobs:
  flatpak:
    name: "Karaberus Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: karaberus.flatpak
        manifest-path: moe.japan7.karaberus.yml
        cache-key: flatpak-builder-${{ github.sha }}
